spring:
  application:
    name: licensingservice
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

spring.zipkin.discoveryClientEnabled: true
spring.zipkin.baseUrl: http://zipkinservice/
spring.sleuth.sampler.probability: 1

management.endpoints.web.exposure.include: '*'

# disable driver's feature detection
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

# without detection you have to set the dialect by hand
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#security:
#  oauth2:
#   resource:
#      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 1 #(2)
  MaxAutoRetriesNextServer: 1 #(3)
  ReadTimeout: 4000 #(4)


#Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG


